import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/theme/Nav/page";
import Footer from "@/components/theme/Footer/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
